# Generated by Django 3.0.5 on 2020-04-01 13:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLineEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='', max_length=300)),
                ('text', models.TextField(default='')),
                ('details_link', models.URLField(default='', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Timeline Entries',
            },
        ),
        migrations.AlterField(
            model_name='barangay',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='case',
            name='pui',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='case',
            name='pum',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BarangayHotline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=15)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barangay_hotline', to='webapp.Barangay')),
            ],
        ),
    ]
